name: Daily Batch Pipeline

on:
  schedule:
    - cron: '30 20 * * *'   # runs daily at 2 AM IST
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingestion
        run: |
          python ingestion/ingest.py
          python ingestion/dim_customer.py

      - name: Transform data
        run: python transformation/transform.py

      - name: Load warehouse
        env:
          Neon_key: ${{ secrets.ENVIRONMENTS}}
        run: |
          python warehouse/load.py
          python warehouse/load_dim_customer.py
